version: '3'

services:
  web:
    image: nginx:latest
    env_file:
      - .env
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ${NGINX_HTML_DIR}:/usr/share/nginx/html
    restart: unless-stopped