---
- hosts: windows
  tasks:
  - name: Install all Windows security updates with automatic reboots
    win_updates:
      category_names:
        - SecurityUpdates
        - CriticalUpdates
      reboot: yes

  # One way to ensure the system is reliable just after a reboot, is to set WinRM to a delayed startup
  - name: Ensure WinRM starts when the system has settled and is ready to work reliably
    win_service:
      name: WinRM
      start_mode: delayed


